[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example"
version = "0.1.0"
requires-python = ">=3.10"

[project.dependencies]
numpy = "^1.21.0"
matplotlib = "^3.4.0"
pandas = "2.2.0"
json = "1.6.3"
  [project]
  dependencies = [
      "numpy>=1.20"
      "matplotlib>=3.4.0"
  ]
[project.optional-dependencies]
test = ["pytest"]

[tool.ruff.lint]
extend-select = [
  "B",
  "UP",
]
