name: Code Formatter Check

on: [push, pull_request]

jobs:
  formatter:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff to check formatting
      run: |
        ruff check . --diff --exit-zero-if-changed
