name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - np6947

jobs:
  tests:
    needs: build
    name: "Tests on Python ${{ matrix.python-version }} for ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - python-version: "3.11"
            runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and test dependencies
        run: pip install -e .[test]

      - name: Run tests
        run: pytest
        
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
        include:
          - python-version: "3.11"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pandas dependency
        run: pip install pandas

      - name: Install requests dependency
        run: pip install requests

      - name: Install pytest-mock dependency
        run: pip install pytest-mock

      - name: Install types-requests
        run: pip install types-requests
      
      - name: Install types-beautifulsoup4
        run: pip install types-beautifulsoup4

      - name: Install pandas-stubs
        run: pip install pandas-stubs

  formatter:
    name: Code Formatter Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff to check formatting
        run: |
          ruff check . --diff --exit-zero

  mypy:
    name: Type Check with mypy
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install mypy
        run: pip install mypy

      - name: Install missing type stubs
        run: mypy --install-types

      - name: Run mypy
        run: mypy src

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files