name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: "Tests on Python ${{ matrix.python-version }} for ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}
    env: 
      PYTHONPATH: /src/apc524-election2024/
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - python-version: "3.11"
            runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pandas dependency
        run: pip install pandas

      - name: Install requests dependency
        run: pip install requests

      - name: Install package and test dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest

  build:
    runs-on: ubuntu-latest
    env: 
      PYTHONPATH: /src/apc524-election2024/
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
        include:
          - python-version: "3.11"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pandas dependency
        run: pip install pandas

      - name: Install requests dependency
        run: pip install requests

  formatter:
    name: Code Formatter Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff to check formatting
        run: |
          ruff check . --diff --exit-zero